{% set version = "0.0.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-discretecdalgorithm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/discretecdAlgorithm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/discretecdAlgorithm/discretecdAlgorithm_{{ version }}.tar.gz
  sha256: 5a6e8d1097c4e32cb9477fb4738b4fda27b96e76b07d8453059bb723a5c3a307

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.11.0
    - r-rcppeigen
    - r-igraph
    - r-sparsebnutils >=0.0.4
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.11.0
    - r-rcppeigen
    - r-igraph
    - r-sparsebnutils >=0.0.4

test:
  commands:
    - $R -e "library('discretecdAlgorithm')"           # [not win]
    - "\"%R%\" -e \"library('discretecdAlgorithm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=discretecdAlgorithm
  license: GPL-2.0-or-later
  summary: Structure learning of Bayesian network using coordinate-descent algorithm. This algorithm is designed for discrete network assuming a multinomial data
    set, and we use a multi-logit model to do the regression. The algorithm is described in Gu, Fu and Zhou (2016) <arXiv:1403.2310>.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
