# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxtarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxtarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "aFK+66O+pSyJaXyoNTeonPPCzH6qSN3IR7LYSM9YMrK+Ex+oqcqjLalyUUlYvcqsigj1BHE44CMOHsF01mXvRy/3gF7xltZlI4OH2d5SV0LenumdpyRcjTdKPzm/rB2xrA1VKDvuCqiFCYLQ3Gx3vU59gWEG3SlOi36ht+CyQ0smnIkYtuLKCKGlkk+5JG3WlWToLSgAEvPqwvlBW9YV55rdwEX1OXXP2qUzWzlek11PCX8E7zFqWlsr7EgHkLMpesb0g56paFd9UE0E8QmfuRMB0L2Rt5z3PP15wX8TR9IooE5KOzRS58wXT9r/eOIoVZeHLbPCm1FBGbO4gl9NkmSWFcJskAgunEpot/268uQgXA5TeAd+UUDx5Rbeq7gNkiQXLXXFqX0QGoV/YAqABbXX1KvrA6qZOjVb/Gch0K2YNKjqtpxNNornYOfbkAOXmRl1NEvuqBuxXzZqSHr8H9ciCXS5pNC9xPOzCsvlZr/VOkZBTR2yw6w6Ql3CKa963alrsAxgBEF0c/gfaHYgdVSDSmkdEzxkHiudLBQPgWFqKQk4lk3bDL72M5/Ms5RP+CsWP73rdDyWn4uhs/l/F4R+9uHAH3smR4AvF4PAmhvPB/Mcf+JOtICAslNLKIYZi59DtRCc1M0Zfv/chBrwcHsRTM7TtEgJW9Ch8t7z8go="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml