appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: aFK+66O+pSyJaXyoNTeonPPCzH6qSN3IR7LYSM9YMrK+Ex+oqcqjLalyUUlYvcqsigj1BHE44CMOHsF01mXvRy/3gF7xltZlI4OH2d5SV0LenumdpyRcjTdKPzm/rB2xrA1VKDvuCqiFCYLQ3Gx3vU59gWEG3SlOi36ht+CyQ0smnIkYtuLKCKGlkk+5JG3WlWToLSgAEvPqwvlBW9YV55rdwEX1OXXP2qUzWzlek11PCX8E7zFqWlsr7EgHkLMpesb0g56paFd9UE0E8QmfuRMB0L2Rt5z3PP15wX8TR9IooE5KOzRS58wXT9r/eOIoVZeHLbPCm1FBGbO4gl9NkmSWFcJskAgunEpot/268uQgXA5TeAd+UUDx5Rbeq7gNkiQXLXXFqX0QGoV/YAqABbXX1KvrA6qZOjVb/Gch0K2YNKjqtpxNNornYOfbkAOXmRl1NEvuqBuxXzZqSHr8H9ciCXS5pNC9xPOzCsvlZr/VOkZBTR2yw6w6Ql3CKa963alrsAxgBEF0c/gfaHYgdVSDSmkdEzxkHiudLBQPgWFqKQk4lk3bDL72M5/Ms5RP+CsWP73rdDyWn4uhs/l/F4R+9uHAH3smR4AvF4PAmhvPB/Mcf+JOtICAslNLKIYZi59DtRCc1M0Zfv/chBrwcHsRTM7TtEgJW9Ch8t7z8go=}
